# Primer Intento de clasificador



Como el titulo lo dice, primer intento de clasificador usando como referencia el laboratorio x .
Se considera para este caso el archivo movies_final_imdb el cual contiene:
    
    movieId+nota_imbd_aprox+duracion+categoria+actores
    
    
Nota : Falta agregar los directores y quizas las fechas para ve como cambia. 

In [1]:
## Librerias
import csv
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.utils import shuffle

# Clasificadores usados : Tree, SVM, RandomForest, Regression, KNN.
from sklearn import tree
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn import linear_model
from sklearn.neighbors import KNeighborsClassifier


from sklearn import cross_validation

Cargamos el archivo 

In [75]:
#Cargamos el Archivo.

movies = pd.read_csv("movies_final.csv", header = 0)
score = pd.read_csv("movielens.csv", header = 0)

movies_header = list(movies.columns.values)
movies = movies.as_matrix()

print movies[4169]

score = np.ravel(score.as_matrix())
movies = movies[0:4160]
score = score[0:4160]


#score = np.asarray(score, dtype="|S6")
#print("Movies:\n", movies[4451])
#print("Score:\n", score[4451])
#print(movies_header)




[102   0   0 ...,   0   0   0]


# KNN basico



In [76]:
# Primer Clasificador : K-nearnest-neighbors

knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(movies, score)
score_pred = knn.predict(movies)
accuracy_score(score, score_pred)

print(classification_report(score,score_pred))

             precision    recall  f1-score   support

        1.0       0.00      0.00      0.00        12
        2.0       0.50      0.24      0.32       407
        3.0       0.68      0.83      0.75      2455
        4.0       0.62      0.46      0.53      1285
        5.0       0.00      0.00      0.00         1

avg / total       0.64      0.66      0.64      4160



## KNN manual


In [14]:
# Primer Clasificador : K-nearnest-neighbors


X_train, X_test, y_train, y_test = cross_validation.train_test_split(movies, score, test_size=0.33)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

print(classification_report(y_test, y_pred))


             precision    recall  f1-score   support

        1.0       0.00      0.00      0.00         3
        2.0       0.21      0.20      0.21       131
        3.0       0.63      0.65      0.64       770
        4.0       0.47      0.47      0.47       416

avg / total       0.54      0.55      0.54      1320



## KNN - Cross Validation

In [5]:
cross_validation.cross_val_score(knn, movies, score, cv=10)


array([ 0.55970149,  0.52736318,  0.515     ,  0.5675    ,  0.5525    ,
        0.5825    ,  0.54636591,  0.51879699,  0.55639098,  0.53132832])

Mejora al momento de reducir las clases

# Support Vector Machine - SVM

In [77]:

movies_svm = svm.SVC()
movies_svm.fit(movies, score)  

score_pred = movies_svm.predict(movies)
accuracy_score(score, score_pred)

print(classification_report(score,score_pred))


             precision    recall  f1-score   support

        1.0       0.00      0.00      0.00        12
        2.0       0.00      0.00      0.00       407
        3.0       0.61      0.95      0.74      2455
        4.0       0.62      0.17      0.26      1285
        5.0       0.00      0.00      0.00         1

avg / total       0.55      0.61      0.52      4160



## SVM con Cross-Validation

In [11]:
svm_cross = svm.SVC()
cross_validation.cross_val_score(svm_cross, movies, score, cv=5)

# cv = 3
# sin_dir : array([ 0.60973783,  0.6024006 ,  0.60735736])
# con_dir : array([ 0.60973783,  0.6024006 ,  0.60735736])


#cv = 5
# sin_dir : array([ 0.62967581,  0.59925094,  0.60450563,  0.59574468,  0.61451815])
# con_dir : array([ 0.62468828,  0.59925094,  0.60325407,  0.59324155,  0.61451815])

#cv = 8
# array([ 0.62674651,  0.61676647,  0.59680639,  0.60479042,  0.598     , 0.602     ,  0.60240964,  0.61646586])

#cv = 2
# array([ 0.6095,  0.6025])


array([ 0.62468828,  0.59925094,  0.60325407,  0.59324155,  0.61451815])

## SVM test set manual

In [78]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(movies, score, test_size=0.80)
#, random_state=37

svm_manual = svm.SVC()
svm_manual.fit(X_train, y_train)
y_pred = svm_manual.predict(X_test)
accuracy_score(y_test, y_pred)


# test_size = 0.5
# sin_dir : 0.60999999999999999
# con_dir : 0.61150000000000004

#test_size = 0.33
# sin_dir : 0.62045454545454548
# con_dir : 0.61212121212121207



0.60336538461538458

In [80]:
#predict toy_story
toy_story = movies[0]
print "\n\nNota original de toy-story : "
print score[0]
#print toy_story
print "Prediccion de nota para toy story:"
print svm_manual.predict([movies[0]])

print "Note original de avatar"
print score[3111]
print "Prediccion par avatar"
print svm_manual.predict([movies[3111]])

print "Nota original Transformers 4"
print score[4057]
print "Prediccion para Transformers 4"
print svm_manual.predict([movies[4057]])



Nota original de toy-story : 
4.0
Prediccion de nota para toy story:
[ 3.]
Note original de avatar
4.0
Prediccion par avatar
[ 4.]
Nota original Transformers 4
3.0
Prediccion para Transformers 4
[ 4.]


-No Acerto a toy-story
-Acertó a avatar
-No acerto a transformers :(


# Random Forest

## Random forest con cross validation.

In [81]:
#Random forest con cross-validation.

forest_cross = RandomForestClassifier(n_estimators=10)
cross_validation.cross_val_score(forest_cross, movies, score, cv=5)

# cv = 3, n = 10
# array([ 0.54456929,  0.57389347,  0.54954955])

# cv = 3, n = 10
# array([ 0.55735661,  0.57927591,  0.59699625,  0.55319149,  0.57446809])



/home/pablo/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:516: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of labels for any class cannot be less than n_folds=5.
  % (min_labels, self.n_folds)), Warning)


array([ 0.54316547,  0.56302521,  0.59085439,  0.5788207 ,  0.57521059])

## Random Forest test set Manual

In [82]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(movies, score, test_size=0.3)
#, random_state=37

forest_manual = RandomForestClassifier(n_estimators=10)
forest_manual.fit(X_train, y_train)
y_pred = forest_manual.predict(X_test)
accuracy_score(y_test, y_pred)


# test_size = 0.33
# 0.57166666666666666

# test_size = 0.5
# 0.55449999999999999


0.57211538461538458

# Arbol de Decision

In [83]:
movies_tree = tree.DecisionTreeClassifier()
cross_validation.cross_val_score(movies_tree, movies, score, cv=10)


/home/pablo/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:516: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of labels for any class cannot be less than n_folds=10.
  % (min_labels, self.n_folds)), Warning)


array([ 0.54415274,  0.53349282,  0.51079137,  0.55395683,  0.51318945,
        0.5373494 ,  0.55903614,  0.56280193,  0.56763285,  0.5410628 ])

Aparentemente, tanto el arbol de decision como random forest tree no tienen un rendimiento mejor que los otros. ¿Por qué?

# Regresion Lineal

In [84]:
reg = linear_model.LinearRegression()
cross_validation.cross_val_score(reg, movies, score, cv=10)

array([ -4.99211098e-01,  -3.31371269e-02,  -2.23027303e-02,
        -3.44575105e+19,  -7.48805208e+02,  -7.35540231e+19,
         1.23895140e-01,  -4.68315809e+20,  -2.00791807e+20,
        -1.59888492e+19])

Esto si que no apaña!!

# Dummy Classifier

Que debemos hacer ahora ? -> Validar los modelos comparandolos con un dummy 