# Primer Intento de clasificador



Como el titulo lo dice, primer intento de clasificador usando como referencia el laboratorio x .
Se considera para este caso el archivo movies_final_imdb el cual contiene:
    
    movieId+nota_imbd_aprox+duracion+categoria+actores
    
    
Nota : Falta agregar los directores y quizas las fechas para ve como cambia. 

In [31]:
## Librerias
import csv
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.utils import shuffle

# Clasificadores usados : Tree, SVM, RandomForest, Regression, KNN.
from sklearn import tree
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn import linear_model
from sklearn.neighbors import KNeighborsClassifier


from sklearn import cross_validation

Cargamos el archivo 

In [5]:
#Cargamos el Archivo.

movies = pd.read_csv("movies_final.csv", header = 0)
score = pd.read_csv("movielens.csv", header = 0)

movies_header = list(movies.columns.values)

movies = movies.as_matrix()



score = np.ravel(score.as_matrix())
movies = movies[0:4000]
score = score[0:4000]


#score = np.asarray(score, dtype="|S6")
#print("Movies:\n", movies[4451])
#print("Score:\n", score[4451])
#print(movies_header)




# KNN basico



In [6]:
# Primer Clasificador : K-nearnest-neighbors

knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(movies, score)
score_pred = knn.predict(movies)
accuracy_score(score, score_pred)

print(classification_report(score,score_pred))

             precision    recall  f1-score   support

        1.0       0.00      0.00      0.00        12
        2.0       0.50      0.17      0.25       392
        3.0       0.68      0.85      0.76      2350
        4.0       0.65      0.48      0.55      1246

avg / total       0.65      0.67      0.64      4000



/home/pablo/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1074: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## KNN manual


In [7]:
# Primer Clasificador : K-nearnest-neighbors


X_train, X_test, y_train, y_test = cross_validation.train_test_split(movies, score, test_size=0.33, random_state=37)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

print(classification_report(y_test, y_pred))


             precision    recall  f1-score   support

        1.0       0.00      0.00      0.00         4
        2.0       0.31      0.26      0.28       141
        3.0       0.62      0.70      0.66       785
        4.0       0.44      0.37      0.40       390

avg / total       0.54      0.55      0.54      1320



## KNN - Cross Validation

In [8]:
cross_validation.cross_val_score(knn, movies, score, cv=10)


array([ 0.56965174,  0.54477612,  0.5075    ,  0.575     ,  0.5725    ,
        0.56      ,  0.55639098,  0.51629073,  0.56390977,  0.58646617])

Mejora al momento de reducir las clases

# Support Vector Machine - SVM

In [11]:

movies_svm = svm.SVC()
movies_svm.fit(movies, score)  

score_pred = movies_svm.predict(movies)
accuracy_score(score, score_pred)

print(classification_report(score,score_pred))


             precision    recall  f1-score   support

        1.0       0.00      0.00      0.00        12
        2.0       0.00      0.00      0.00       392
        3.0       0.61      0.94      0.74      2350
        4.0       0.62      0.19      0.30      1246

avg / total       0.55      0.61      0.53      4000



## SVM con Cross-Validation

In [14]:
svm_cross = svm.SVC()
cross_validation.cross_val_score(svm_cross, movies, score, cv=8)

# cv = 3
# array([ 0.60973783,  0.6024006 ,  0.60735736])


#cv = 5
# array([ 0.62967581,  0.59925094,  0.60450563,  0.59574468,  0.61451815])

#cv = 8
# array([ 0.62674651,  0.61676647,  0.59680639,  0.60479042,  0.598     ,
        0.602     ,  0.60240964,  0.61646586])

#cv = 2
# array([ 0.6095,  0.6025])


array([ 0.62674651,  0.61676647,  0.59680639,  0.60479042,  0.598     ,
        0.602     ,  0.60240964,  0.61646586])

## SVM test set manual

In [16]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(movies, score, test_size=0.5)
#, random_state=37

svm_manual = svm.SVC()
svm_manual.fit(X_train, y_train)
y_pred = svm_manual.predict(X_test)
accuracy_score(y_test, y_pred)


# test_size = 0.5
# 0.60999999999999999

#test_size = 0.3
# 0.62045454545454548



0.60999999999999999

In [23]:
#predict toy_story
toy_story = movies[0]
print "\n\nNota original de toy-story : "
print score[0]
#print toy_story
print "Prediccion de nota para toy story:"
svm_manual.predict([movies[0]])



Nota original de toy-story : 
4.0
Prediccion de nota para toy story:


array([ 3.])

No Acertó :(

# Random Forest

## Random forest con cross validation.

In [25]:
#Random forest con cross-validation.

forest_cross = RandomForestClassifier(n_estimators=10)
cross_validation.cross_val_score(forest_cross, movies, score, cv=5)

# cv = 3, n = 10
# array([ 0.54456929,  0.57389347,  0.54954955])

# cv = 3, n = 10
# array([ 0.55735661,  0.57927591,  0.59699625,  0.55319149,  0.57446809])



array([ 0.55735661,  0.57927591,  0.59699625,  0.55319149,  0.57446809])

## Random Forest test set Manual

In [27]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(movies, score, test_size=0.3)
#, random_state=37

forest_manual = RandomForestClassifier(n_estimators=10)
forest_manual.fit(X_train, y_train)
y_pred = forest_manual.predict(X_test)
accuracy_score(y_test, y_pred)


# test_size = 0.33
# 0.57166666666666666

# test_size = 0.5
# 0.55449999999999999


0.57166666666666666

# Arbol de Decision

In [28]:
movies_tree = tree.DecisionTreeClassifier()
cross_validation.cross_val_score(movies_tree, movies, score, cv=10)


array([ 0.54975124,  0.52985075,  0.54      ,  0.5525    ,  0.5625    ,
        0.56      ,  0.53132832,  0.54135338,  0.54887218,  0.5839599 ])

Aparentemente, tanto el arbol de decision como random forest tree no tienen un rendimiento mejor que los otros. ¿Por qué?

# Regresion Lineal

In [32]:
reg = linear_model.LinearRegression()
cross_validation.cross_val_score(reg, movies, score, cv=10)

array([-0.2997575 ,  0.15327058,  0.01197338,  0.00139756,  0.10451518,
        0.05117237,  0.14274102,  0.09868757,  0.06867603,  0.09969581])

# Dummy Classifier

Que debemos hacer ahora ? -> Validar los modelos comparandolos con un dummy 